Surface problems with overrides and fallback (#3711)
Contributes to #3658

We have very large statements initializing individual fields in object
GpuOverrides. They may easily generate uncaught exceptions that are later
surfaced as an obscure `NoClassDefFoundError` for `GpuOVerrides$ class`
initialization
- catch and log root cause exceptions
- fallback on CPU if overrides failed on a NonFatal exception
- re-throw on fatal

`useBaseVersion` for the cudf jar so we don't have to modify the notebook config often.

Signed-off-by: Gera Shegalov <gera@apache.org>