Handle minimum GPU architecture supported [databricks] (#10540)
Fixes #10430. This PR ensures that Spark RAPIDS jobs are executed on supported GPU architectures without relying on manual configuration. 

### Changes:
1. Processes `gpu_architectures` property from the `*version-info.properties` file generated by the native builds. 
2. Verifies if the user is running the job on an architecture supported by the cuDF and JNI libraries and throws an exception if the architecture is unsupported.

### Testing
Tested on a Dataproc VM running on Nvidia P4 (GPU Architecture 6.1)

```
24/03/06 17:44:58 WARN RapidsPluginUtils: spark.rapids.sql.explain is set to `NOT_ON_GPU`. Set it to 'NONE' to suppress the diagnostics logging about the query placement on the GPU.
24/03/06 17:45:10 ERROR RapidsExecutorPlugin: Exception in the executor plugin, shutting down!
java.lang.RuntimeException: Device architecture 61 is unsupported. Minimum supported architecture: 75.
        at com.nvidia.spark.rapids.RapidsPluginUtils$.checkGpuArchitectureInternal(Plugin.scala:366)
        at com.nvidia.spark.rapids.RapidsPluginUtils$.checkGpuArchitecture(Plugin.scala:375)
        at com.nvidia.spark.rapids.RapidsExecutorPlugin.init(Plugin.scala:461)
```


### Related PR
* https://github.com/NVIDIA/spark-rapids-jni/pull/1840
* Add conf for minimum supported CUDA and error handling

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Revert "Add conf for minimum supported CUDA and error handling"

This reverts commit 7b8eaeaf4c0f3f9c6d781602eb59eb19c823dca0.

* Verify the GPU architecture is supported by the plugin libraries

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Use semi-colon as delimiter and use intersection of supported gpu architectures

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Allow for compatibility with major architectures

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Check for version as integers

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Modify compatibility check for same major version and same or higher minor version

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Add a config to skip verification and refactor checking

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Update RapidsConf.scala

Co-authored-by: Jason Lowe <jlowe@nvidia.com>

* Update verification logic

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Update warning message

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Add unit tests and update warning message.

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Update exception class

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

* Address review comments

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>

---------

Signed-off-by: Partho Sarthi <psarthi@nvidia.com>
Co-authored-by: Jason Lowe <jlowe@nvidia.com>