Use alluxio Java API to mount instead of cmd [databricks] (#6824)
* Use alluxio native mount instead of cmd

Signed-off-by: Chong Gao <res_life@163.com>

Upate

* Update

Signed-off-by: Chong Gao <res_life@163.com>

* Update log

Signed-off-by: Chong Gao <res_life@163.com>

* Update

Signed-off-by: Chong Gao <res_life@163.com>

* Update

Signed-off-by: Chong Gao <res_life@163.com>

* Update doc

* Fix compile error for alluxio client version 2.8.1

* Refactor

* Refactor

* Move alluxio config related code to a new place to solve NoClassDefFoundError in MortgageSparkSuite

* Fix Unused import

* Fix NoClassDefFoundError

* Fix comments

Signed-off-by: Chong Gao <res_life@163.com>
Co-authored-by: Chong Gao <res_life@163.com>