Propagate errors to JVM while initializing GPU memory in python worker (#12688)
Fixes https://github.com/NVIDIA/spark-rapids/issues/12608.

This PR adds an error propagation mechanism for the errors occurred
while initializing GPU memory for python workers. Previously, if an
error occurs while initializing GPU memory (more properly speaking any
errors in the `initialize_gpu_mem()` function), the JVM stack trace used
to show only the `EOFException` that was caused by the python process
stopped which in turn closed the socket connection to the Java process.
One example of such stack traces can be found in #12566. After this PR,
the stack trace now shows the error from the python side properly. The
below shows the python error propagated to the JVM side when the same
import error as the one in #12566 occurs.

```
=========================== short test summary info ============================
FAILED ../../src/main/python/udf_cudf_test.py::test_with_column[small data][DATAGEN_SEED=1746825161, TZ=UTC, INJECT_OOM] - py4j.protocol.Py4JJavaError: An error occurred while calling o488.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1.0 failed 1 times, most recent failure: Lost task 1.0 in stage 1.0 (TID 5) (10.110.47.50 executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/home/jihoons/Projects/spark-rapids/dist/target/rapids-4-spark_2.12-25.06.0-SNAPSHOT-cuda12.jar/rapids/daemon.py", line 77, in worker
    initialize_gpu_mem()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/jihoons/Projects/spark-rapids/dist/target/rapids-4-spark_2.12-25.06.0-SNAPSHOT-cuda12.jar/rapids/worker.py", line 27, in initialize_gpu_mem
    from cudf import rmm
ImportError: cannot import name 'rmm' from 'cudf' (/home/jihoons/miniforge3/envs/cudf_dev/lib/python3.13/site-packages/cudf/__init__.py)

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:572)
	at org.apache.spark.sql.rapids.execution.python.shims.GpuArrowPythonOutput$$anon$1.read(GpuArrowPythonOutput.scala:105)
	at org.apache.spark.sql.rapids.execution.python.shims.GpuArrowPythonOutput$$anon$1.read(GpuArrowPythonOutput.scala:73)
...
```

Once the GPU memory is initialized, we call the `main()` function in
`pyspark/worker.py` in Apache Spark. Any errors occurred in this
function are already being handled properly in the Spark implementation
and we don't have to worry about propagating them.

Unlike what was suggested in #12608, it doesn't seem to me that this
change will help with the cases like #12603. #12603 is about process
hangs due to some potential bug in the pyarrow library. The test in
question writes some data first with pyarrow and tries to read it back
with the plugin (and the other way around as well). This test doesn't
seem to involve the python worker in its testing.

---------

Signed-off-by: Jihoon Son <ghoonson@gmail.com>