Update supported exprs and docs to fix build error [skip ci] (#12290)
This PR is to update supported exprs for Shim 355 and docs to fix CI/CD
build errors.
The error for the shim supported expression missing is after
https://github.com/NVIDIA/spark-rapids/pull/12178 was merged.
We added shim355 in 25.02.1 and then upmerged it to 25.04. 
This PR-https://github.com/NVIDIA/spark-rapids/pull/12178 was created on
02/19 and was merged today 03/06. Since it was not upmerged with the
latest 25.02 branch, it was missing 355 shims info.

Fixes error:
```
found modified files during mvn verify:
 M tools/generated_files/355/supportedExprs.csv
Error:  Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

Signed-off-by: Niranjan Artal <nartal@nvidia.com>