Refactor SparkSession to fix Spark-4.0 build (#12227)
This contributes to build issue
https://github.com/NVIDIA/spark-rapids/issues/12062 and is a follow up
of https://github.com/NVIDIA/spark-rapids/pull/12198.

Spark made package name update in Spark-4.0 for SparkSession to support
connect.
In this PR, we added support to pick the correct SparkSession for
different Spark versions.
For Spark version < 4.0 -  It is org.apache.spark.sql.SparkSesssion
For Spark version 4.0 -  It is org.apache.spark.sql.classic.SparkSession

In addition to the package name change, sqlContext is removed from
Dataframe. Have updated the `InternalColumnarRddConverter.scala` file
accordingly.

**Before this change:**

```
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark332db/scala/org/apache/spark/sql/rapids/shims/GpuDataSource.scala:90: type mismatch;
 found   : org.apache.spark.sql.catalyst.TableIdentifier
 required: String
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark350db143/scala/com/nvidia/spark/rapids/shims/PartitionedFileUtilsShim.scala:38: not enough arguments for method splitFiles: (file: org.apache.spark.sql.execution.datasources.FileStatusWithMetadata, filePath: org.apache.hadoop.fs.Path, isSplitable: Boolean, maxSplitBytes: Long, partitionValues: org.apache.spark.sql.catalyst.InternalRow): Seq[org.apache.spark.sql.execution.datasources.PartitionedFile].
Unspecified value parameter partitionValues.
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark400/scala/org/apache/spark/sql/execution/rapids/shims/FilePartitionShims.scala:29: not enough arguments for method getPartitionedFile: (file: org.apache.spark.sql.execution.datasources.FileStatusWithMetadata, filePath: org.apache.hadoop.fs.Path, partitionValues: org.apache.spark.sql.catalyst.InternalRow, start: Long, length: Long): org.apache.spark.sql.execution.datasources.PartitionedFile.
Unspecified value parameter length.
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark400/scala/org/apache/spark/sql/hive/rapids/shims/CommandUtilsShim.scala:30: type mismatch;
 found   : SparkSession (in org.apache.spark.sql) 
 required: SparkSession (in org.apache.spark.sql.classic) 
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark400/scala/org/apache/spark/sql/nvidia/DFUDFShims.scala:24: object ExpressionUtils is not a member of package org.apache.spark.sql.internal
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark400/scala/org/apache/spark/sql/nvidia/DFUDFShims.scala:27: not found: value expression
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark400/scala/org/apache/spark/sql/nvidia/DFUDFShims.scala:28: not found: value column
[ERROR] 16 errors found
```

**After this change:**

```
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark350db143/scala/com/nvidia/spark/rapids/shims/PartitionedFileUtilsShim.scala:38: not enough arguments for method splitFiles: (file: org.apache.spark.sql.execution.datasources.FileStatusWithMetadata, filePath: org.apache.hadoop.fs.Path, isSplitable: Boolean, maxSplitBytes: Long, partitionValues: org.apache.spark.sql.catalyst.InternalRow): Seq[org.apache.spark.sql.execution.datasources.PartitionedFile].
Unspecified value parameter partitionValues.
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/spark400/scala/org/apache/spark/sql/execution/rapids/shims/FilePartitionShims.scala:29: not enough arguments for method getPartitionedFile: (file: org.apache.spark.sql.execution.datasources.FileStatusWithMetadata, filePath: org.apache.hadoop.fs.Path, partitionValues: org.apache.spark.sql.catalyst.InternalRow, start: Long, length: Long): org.apache.spark.sql.execution.datasources.PartitionedFile.
Unspecified value parameter length.
[ERROR] two errors found
```

---------

Signed-off-by: Niranjan Artal <nartal@nvidia.com>