Refactor SparkStrategy to fix Spark-4.0 build (#12198)
This contributes to https://github.com/NVIDIA/spark-rapids/issues/12062.
This fixes the spark-plugin-api module and also fixes some of the build
failures in spark-plugin module which had reference to SparkStrategy. We
import from SparkStrategy directly instead of an alias `Strategy`.

These failures are fixed now:

```
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/SQLExecPlugin.scala:19: object Strategy is not a member of package org.apache.spark.sql
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/SQLExecPlugin.scala:27: not found: type Strategy
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala:30: object Strategy is not a member of package org.apache.spark.sql
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin-api/src/main/scala/com/nvidia/spark/rapids/ShimLoader.scala:354: not found: type Strategy
[ERROR] four errors found



[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:21: object Strategy is not a member of package org.apache.spark.sql
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:30: not found: type Strategy
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:32: not found: type Strategy
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala:21: object Strategy is not a member of package org.apache.spark.sql
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala:44: not found: type Strategy
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:43: value nonEmpty is not a member of Nothing
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/StrategyRules.scala:32: private val strategies in class StrategyRules is never used
Applicable -Wconf / @nowarn filters for this fatal warning: msg=<part of the message>, cat=unused-privates, site=com.nvidia.spark.rapids.StrategyRules.strategies
[ERROR] [Error] /home/nartal/spark-rapids-2504/spark-rapids/sql-plugin/src/main/scala/com/nvidia/spark/rapids/delta/DeltaProvider.scala:100: not found: type Strategy

```
---------

Signed-off-by: Niranjan Artal <nartal@nvidia.com>