Fix the failures in array_test.py for Spark 400[databricks] (#12955)
close https://github.com/NVIDIA/spark-rapids/issues/11007

There are two kinds of failures here
1) `a[5]` sometimes throws out an exception because the index 5 is out
of bounds when the generated array has less than 5 elements. So we make
sure the array is either a null or has 6 elements at least.
```
pyspark.errors.exceptions.captured.ArrayIndexOutOfBoundsException: [INVALID_ARRAY_INDEX] The index 5 is out of bounds. The array has 3 elements. Use the SQL function `get()` to tolerate accessing element at invalid index and return NULL instead. SQLSTATE: 22003
```

2) The error message changes for invalid cases, so update it
accordingly.

---------

Signed-off-by: Firestarman <firestarmanllc@gmail.com>