Surface problems with overrides and fallback
Contributes to #3658

We have very large statement initializing in individual fields in object
GpuOverrides, they may generate uncaught excpetions that are later
surfaced as an obscure NoClassDefFoundError for GpuOVerrides$ class
initialization
- catch and log root cause exceptions
- fallback on CPU if overrides don't work

Signed-off-by: Gera Shegalov <gera@apache.org>