Crash pytest worker if the Pyspark child JVM is unusable (#12455)
Resolves #12454 

This PR uses the spark-job-timeout fixture as a keep alive ping.
On any exception to `setSparkJobTimeout` (which is a trivial setter
```Java
  public static void setSparkJobTimeout(int ts, boolean dumpThreads) {
    timeoutSeconds = ts;
    shouldDumpThreads = dumpThreads;
  }
``` 
and it is fair to assume that the child JVM is unusable) we issue a hard
exit on the PySpark Python driver.

This triggers xdist to restart the worker and the previously misreported
pytest items are resubmitted to the restarted worker and they succeed if
simply misreported.

With this PR we get an accurate report containing only the Parquet LZ4
test failures due to #12453

```
DATAGEN_SEED=1743895597  TEST_TAGS='not premerge_ci_1' TEST_TYPE=pre-commit TESTS='parquet_testing_test.py' SPARK_HOME=~/dist/spark-3.2.0-bin-hadoop3.2 ./integration_tests/run_pyspark_from_build.sh --test_oom_injection_mode=never 
================================================================================================================================================================================== short test summary info ===================================================================================================================================================================================
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_valid_files[confs0-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/hadoop_lz4_compressed.parquet][DATAGEN_SEED=1743895597, TZ=UTC]
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_valid_files[confs0-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/hadoop_lz4_compressed_larger.parquet][DATAGEN_SEED=1743895597, TZ=UTC]
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_valid_files[confs1-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/hadoop_lz4_compressed.parquet][DATAGEN_SEED=1743895597, TZ=UTC]
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_valid_files[confs1-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/hadoop_lz4_compressed_larger.parquet][DATAGEN_SEED=1743895597, TZ=UTC]
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_error_files[confs0-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/non_hadoop_lz4_compressed.parquet-Exception][DATAGEN_SEED=1743895597, TZ=UTC] - AssertionError: Expected error 'Exception' did not appear in 'ConnectionRefusedError: [Errno 111] Connection refused'
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_error_files[confs0-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/non_hadoop_lz4_compressed.parquet-Exception][DATAGEN_SEED=1743895597, TZ=UTC]
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_error_files[confs1-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/non_hadoop_lz4_compressed.parquet-Exception][DATAGEN_SEED=1743895597, TZ=UTC] - AssertionError: Expected error 'Exception' did not appear in 'ConnectionRefusedError: [Errno 111] Connection refused'
FAILED ../../src/main/python/parquet_testing_test.py::test_parquet_testing_error_files[confs1-/home/gshegalov/gits/NVIDIA/spark-rapids/thirdparty/parquet-testing/data/non_hadoop_lz4_compressed.parquet-Exception][DATAGEN_SEED=1743895597, TZ=UTC]
============================================================================================================================================================= 8 failed, 70 passed, 20 xfailed, 4 xpassed, 108 warnings in 33.49s =============================================================================================================================================================
```

---------

Signed-off-by: Gera Shegalov <gshegalov@nvidia.com>